# Generated by Django 6.0.4 on 2026-05-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_backfill_userprofiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
