# Generated by Django 6.0.5 on 2026-05-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_user_profile_delete_event'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friendrequest',
            table='accounts_friendrequest',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='accounts_profile',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='accounts_userprofile',
        ),
    ]
