# Generated by Django 6.0.5 on 2026-05-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_db_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friendrequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
