# Generated by Django 6.0.3 on 2026-04-09 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='events_shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
