# Generated by Django 6.0.5 on 2026-05-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventseries_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseries',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
